pipelines:
  blogsite:
    group: abc
    materials:
      blogsite:
        git: https://github.com/paulaylingdev/blogsite.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: python
                    arguments:
                      - setup.py
                      - test
